name: Peugeot 2008 Bot
on:
  schedule:
    - cron: '0 * * * *' # Изпълнява се на всеки час
  workflow_dispatch: # Позволява ръчно пускане

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run Scraper
        env:
          YAHOO_USER: ${{ secrets.YAHOO_USER }}
          YAHOO_PASS: ${{ secrets.YAHOO_PASS }}
        run: python scraper.py
        
      - name: Commit changes (database update)
        run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@github.com'
          git add seen_ads.txt
          git commit -m "Update seen ads" || exit 0
          git push
